name: cutde
channels:
  - conda-forge
dependencies:
  # Used for cutde
  - numpy
  - scipy
  - matplotlib
  - pyproj

  # Developer tools
  - pre-commit
  - black
  - flake8
  - isort
  - pytest
  - pytest-cov
  - ipdb
  - pip
  - twine

  # build tools
  - c-compiler
  - cxx-compiler
  - pybind11
  - mako
