name: cutde
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pyproj
  - proj
  - black
  - flake8
  - isort
  - pytest
  - pytest-cov
  - pre-commit
  - ipdb
  - pip
  - mako
