{% set version = "21.8.11" %}
{% set name = "cutde" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cutde-{{ version }}.tar.gz
  git_url: ../
  # sha256: c3ccf16c62580a941e4fee2e753748f164fa154dc835d0b0bb94de0d61829a11

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  skip: True # [py<37]
  skip: True # [win]

requirements:
  build:
    - python
    - numpy
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - pybind11
    - mako

  host:
    - python
    - numpy
    - pip
    - llvm-openmp  # [osx]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pyproj
    - mako

test:
  imports:
    - cutde
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tbenthompson/cutde
  summary: 130 million TDEs per second, Python + CUDA TDEs from Nikkhoo and Walter 2015
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tbenthompson
