name: Test macOS pip install

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-macos-pip:
    name: Test pip install on macOS
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
      with:
        # Full history is required for setuptools-scm to determine version
        fetch-depth: 0
    - uses: mamba-org/setup-micromamba@v1
      with:
        create-args: >-
          python=3.12.*
          pip
    - name: Install cutde via pip
      run: pip install cutde
